name: Generate Baseline Profile

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: macos-latest  # Use macOS for hardware acceleration
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create Keystore
        run: echo "${{ secrets.KEYSTORE_FILE }}" | base64 -d > app/keystore.jks

      - name: Create local.properties
        run: |
          echo "Creating local.properties file"
          echo "KEYSTORE_PATH=keystore.jks" > local.properties
          echo "KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}" >> local.properties
          echo "KEY_ALIAS=${{ secrets.KEY_ALIAS }}" >> local.properties
          echo "KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}" >> local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Generate Baseline Profile
        run: ./gradlew :app:generateBaselineProfile

      - name: Copy Baseline and Startup Profiles
        run: |
          cp app/src/googlePlayRelease/generated/baselineProfiles/baseline-prof.txt app/src/main/baseline-prof.txt
          cp app/src/googlePlayRelease/generated/baselineProfiles/startup-prof.txt app/src/main/startup-prof.txt

      - name: Commit Baseline Profile
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git checkout -b update-baseline-profile
          git add app/src/main/baseline-prof.txt
          git add app/src/main/startup-prof.txt
          git commit -m "Update Baseline Profile"
          git push origin update-baseline-profile
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: update-baseline-profile
          base: master
          title: "Update Baseline Profile"
          body: "This PR updates the Baseline Profile file."